export const bucketList = [
  `Take a picture near the front of Royce and upload it to your LinkedIn.`,
  `Catch a movie premiere in Westwood with a few friends and meet the stars.`,
  `Rub the Bruin Bear's paw for good luck on Bruin Walk on your way to an exam.`,
  `Bathe yourself in the Inverted Fountain on the day of graduation.`,
  `Go to a free local concert.`,
  `Take a nap right by Janss steps.`,
  `Flyer on Bruin Walk.`,
  `Get flyered on Bruin Walk.`,
  `Go to a football game and get your hopes up for a better season, then be disappointed yet again.`,
  `Find a few Birds and flock up with your friends down Westwood Blvd.`,
  `Go to Powell, YRL, or your favorite library and just study there all day.`,
  `Go to CEC and CAC's Bruin Bash — at least once.`,
  `Go tunnelling!`,
  `Go to the Westwood Farmers Market on Thursday and support your local farmers.`,
  `Do the Hollywood hike with some friends, or a date, and breathe in that fresh LA air.`,
  `Volunteer for some community service with the Community Service Commission or do Volunteer Day again as a 2nd, 3rd, or 4th year.`,
  `Play a game of Ultimate Frisbee or Disc Golf on campus.`,
  `Go to a specialty film premiere.`,
  `Get a dozen, day old-Diddy Riese cookies.`,
  `Send a high school friend that goes to a different college a care package or photo book to show how much you love and miss them.`,
  `Catch up with an old friend over coffee at Kerckhoff coffee house.`,
  `Sit on the sidewalk and eat something from your fav food truck at First Fridays in Venice.`,
  `Pretend you're famous by taking an extra af pic at LACMA. And get disappointed by the size of the lights.`,
  `Buy tickets and go to a concert in LA (The Shrine Expo Hall, The Novo, Disney Concert Hall, Hollywood Bowl, The Fonda). Everyone performs here, tbh.`,
  `Visit a friend at U$C and just make fun of them the whole time for going to U$C.`,
  `Have a beach day in Santa Monica.`,
  `Go to Spring Sing and get a sense of how damn talented everyone here is.`,
  `Walk around in the botanical garden and find the lil froggies!`,
  `Crack a cold one with the boys/girls/boys and girls.`,
  `Crack a ~few cold ones with the boys/girls/boys and girls.`,
  `Throw a birthday surprise party for one of your best friends.`,
  `Go to an a cappella concert and accept that some people are just way better than you at singing.`,
  `Go to a basketball game and get absolutely rowdy.`,
  `Go cliff jumping up at Malibu Creek and have someone take a video of it so you could then post it on social media and show off how outdoorsy you are.`,
  `Climb up on the Bruin Bear and pose obnoxiously.`,
  `Climb on a rooftop of a UCLA building.`,
  `Go to Karaoke Night and show everyone why you aren't the next Ed Sheeran or Beyonce.`,
  `Attend a student protest and fight for what you think is right!`,
  `Host a potluck and invite your friends over to the apartment you spent months on trying to find.`,
  `Get a picture with Joe Bruin or Josephine Bruin.`,
  `Join one or more of the 1,000+ clubs.`,
  `After you join one or more of the 1,000+ clubs, go on a retreat!`,
  `Have a food extravaganza in Sawtelle, K-town, Westwood, Santa Monica, DTLA, etc.`,
  `Spend your life's savings on a Spring Break trip with your friends because those memories will honestly last forever.`,
  `Roller Skate or Bike down the beach path on Venice boardwalk or Santa Monica.`,
  `Try to become an influencer, of anything, cuz L.A.`,
  `Have a freshman floor reunion and invite your old floor mates.`,
  `Drive down PCH to Malibu and feel so damn SoCal.`,
  `Take at least one “this looks cool” class just for the hell of it.`,
  `Invite an out-of-state or international student over to your parents' home for Thanksgiving.`,
  `Spend a night ON campus.`,
  `Strip down and do the Undie Run on Wednesday night of Finals Week`,
  `Get to know your college counselor/advisor and have them help you plan out your career.`,
  `Have everyone take the Rice Purity Test at a bonfire at Dockweiler Beach.`,
  `Drop a class way too late in the quarter.`,
  `Go to a free live show taping.`,
  `Get a beer flight at the Ralph's Bar with your friends.`,
  `Read one of the numerous books about the legendary coach, John Wooden.`,
  `Call home every once in awhile, people do actually miss you.`,
  `Befriend someone in UCLA Tours and take a campus tour, you'll be surprised at how many fun facts you didn't know.`,
  `Visit the Griffith Observatory after or before you do the Hollywood hike.`,
  `Visit one of the numerous taco trucks in LA (like Leo's or El Matador).`,
  `Go do the Student Wellness Commission's Bruin Run/Walk and get your 5K in for the day to support Mattel Children's Hospital!`,
  `Get as much free stuff as you can at the Enormous Activities Fair.`,
  `Join an IM team and shoot for getting the free shirts at the championship game.`,
  `Make out with a summer fling in the sculpture garden.`,
  `Donate blood. Or at least try to donate to the UCLA Blood and Platelet Center.`,
  `Get hired for an internship so you can get a glimpse of what the real world is like.`,
  `KBBQ!`,
  `Study abroad!`,
  `Get a squad together to go kayaking at Marina Del Rey.`,
  `Take a free trip to The Getty or The Hammer and appreciate the beauty but not really understand the artwork.`,
  `Go to the UCLA Athletic Hall of fame and feel proud to be a bruin.`,
  `Pull an all nighter to finish an assignment. Are you even a college student if you haven't done this?`,
  `Pull an all nighter for no reason. Find a rooftop, pick a friend, and talk about everything.`,
  `Take a summer class or two during A-session or C-session to lighten up the course load during the academic year.`,
  `Walk around campus alone around sundown and really enjoy the beauty of this campus.`,
  `Befriend a professor. Surprisingly, some of them are actually pretty cool.`,
  `After you befriend a professor, subtly beg them for a letter of recommendation for Grad school or internship applications.`,
  `Scream your heart out during finals week every midnight for the midnight yell and try to avoid getting written up for it.`,
  `Go slacklining in between two trees next to Janss steps.`,
  `Walk into every…single….damn…building at UCLA just to say you did.`,
  `Hit up a friend that you met during Orientation.`,
  `Actually go to office hours and actually ask questions.`,
  `Learn another language and show off your skills to a friend that's a native speaker.`,
  `Go 26 hours straight at Dance Marathon!!`,
  `Have a friend with a DSLR take a ba$ic photo of you in front of the ba$ic pink wall on Melrose Ave.`,
  `After that, take another basic photo, but this time holding a bowl Saffron and Rose ice cream.`,
  `Try to go viral by posting a meme on the UCLA Memes for Sick AF Tweens FB page.`,
  `Actually go to an event or lecture inside Royce Hall and understand how freaking huge it is on the inside too.`,
  `Swipe your family in for food in our #1 Nationally Ranked Dining Halls.`,
  `Go to Cultural Affairs Commission's JazzReggae Festival.`,
  `Go meditate by the creek near Anderson School of Management.`,
  `Do something amazing and get published in the Daily Bruin newspaper.`,
  `Play volleyball at Sunset Rec, or racquetball at Wooden with some friends.`,
  `DE NEVE LATE NIGHT CHICKEN TENDIES!`,
  `Get a wowshi from Bella Pita at 2:30AM after being disappointed that In N' Out is already closed.`,
  `Start an 8-clap at a football game because apparently it's the only place that's socially acceptable for students to start an 8-clap after the first week of freshman year.`,
  `Find a random book at Powell Library and just spend all day reading it on a bean bag chair in the bookstacks.`,
  `Find your special area on campus, the place where you feel most at peace, and be proud to go to this amazing school.`
]

export const copy = {
  title: 'The Bruin Bucket List',
  sourceCitation: {
    text: "Based on George Faour's awesome Medium article",
    link:
      'https://medium.com/@georgefaour/100-things-to-do-before-graduating-from-ucla-9b4e16a48730'
  },
  instructions:
    'Click items to check them off. Your progress is automatically saved to your browser.'
}
